comment:
  on-update: edit
  header: |
    Thank you for contributing to `exercism/elixir` :purple_heart:. This is an automated PR comment for the **maintainers** of this repository and you can just ignore it.

    Based on the files changed in this PR, the following manual steps should be taken when reviewing the PR:

  footer: |
    ---
    Automated comment created by [PR Commenter](https://github.com/angelikatyborska/pr-commenter-action).

  snippets:
    - id: any-file-changed
      files:
        - '*'
        - '**/*'
      body: |
        - **General steps**
            - Should this PR receive a label with a reputation modifier (`reputation/contributed_code/{minor,major}`)?

    - id: any-exercise-changed
      files:
        - 'exercises/**/*'
      body: |
        - **Any exercise changed**
            - Should the author of the PR be added to `contributors` in `<exercise>/.meta/config.json`?
            - Do the [analyzer](https://github.com/exercism/elixir-analyzer/tree/main/test/elixir_analyzer/test_suite) and the [analyzer comments](https://github.com/exercism/website-copy/tree/main/analyzer-comments/elixir) exist for this exercise? Do they need to be changed?
            - Should the design file (`<exercise>/.meta/design.md`) be updated to document new implementation decisions?

    - id: practice-exercise-changed
      files:
        - 'exercises/practice/**/*'
      body: |
        - **Practice exercise changed**
            - Should `prerequisites`, `practices`, and `difficulty` in `config.json` be updated?
            - Are the changes in accordance with [problem specifiations](https://github.com/exercism/problem-specifications/tree/main/exercises)?

    - id: practice-exercise-tests-changed
      files:
        - 'exercises/practice/**/test/**/*'
      body: |
        - **Practice exercise tests changed**
            - Are all tests but the first one _skipped_?
            - Does `<exercise>/.meta/tests.toml` need updating?

    - id: concept-exercise-changed
      files:
        - 'exercises/concept/**/*'
      body: |
        - **Concept exercise changed**
            - Should `prerequisites` and `practices` in `config.json` be updated?
            - Does the concept introduction provide all necessary information to solve this exercise?

    - id: concept-exercise-test-changed
      files:
        - 'exercises/concept/**/test/**/*'
      body: |
        - **Concept exercise tests changed**
            - Are all tests _un-skipped_?

    - id: concept-changed
      files:
        - 'concepts/**/*'
      body: |
        - **Concept changed**
            - Should the author of the PR be added to `contributors` in `<concept>/.meta/config.json`?
            - Does the concept introduction provide all necessary information to solve this exercise?
