defmodule RelativeDistance do
  @doc """
  TODO: add function description and replace types in @spec
  """
  @spec degree_of_separation(
          family_tree :: %{
            ian: TODO.t(),
            tariq: TODO.t(),
            umar: TODO.t(),
            yuki: TODO.t(),
            viktor: TODO.t(),
            pedro: TODO.t(),
            wang: TODO.t(),
            tomoko: TODO.t(),
            diego: TODO.t(),
            elif: TODO.t(),
            liam: TODO.t(),
            farah: TODO.t(),
            jing: TODO.t(),
            aiko: TODO.t(),
            uma: TODO.t(),
            hana: TODO.t(),
            zara: TODO.t(),
            zane: TODO.t(),
            sofia: TODO.t(),
            boris: TODO.t(),
            hassan: TODO.t(),
            aditi: TODO.t(),
            ravi: TODO.t(),
            leila: TODO.t(),
            mateo: TODO.t(),
            giorgio: TODO.t(),
            vera: TODO.t(),
            nia: TODO.t(),
            olga: TODO.t(),
            rami: TODO.t(),
            qi: TODO.t(),
            bao: TODO.t(),
            elias: TODO.t(),
            carlos: TODO.t(),
            gustavo: TODO.t(),
            oscar: TODO.t(),
            isla: TODO.t(),
            quynh: TODO.t(),
            khadija: TODO.t(),
            sven: TODO.t(),
            javier: TODO.t(),
            fatima: TODO.t(),
            xia: TODO.t(),
            yassin: TODO.t(),
            wyatt: TODO.t(),
            dalia: TODO.t(),
            mina: TODO.t(),
            noah: TODO.t(),
            priya: TODO.t(),
            xiomara: TODO.t(),
            celine: TODO.t(),
            kaito: TODO.t()
          },
          person_a :: TODO.t(),
          person_b :: TODO.t()
        ) :: TODO.t()
  def degree_of_separation(family_tree, person_a, person_b) do
  end
end
