name: PR Comment

on: [pull_request_target]

jobs:
  pr-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: angelikatyborska/pr-commenter-action@97e4da967b377bf97ce50bfa102a39c8decf4ace
        with:
          github-token: "${{ github.token }}"
          config-file: ".github/pr-commenter.yml"
