name: PR Comment

on: [pull_request_target]

jobs:
  pr-comment:
    runs-on: ubuntu-22.04
    steps:
      - uses: exercism/pr-commenter-action@v1.5.1
        with:
          github-token: "${{ github.token }}"
          config-file: ".github/pr-commenter.yml"
